config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :sellers

  get 'welcome/index'
  get 'register' => 'sellers#new', :as => :register
  get '/sellers/:action(/:seller_id)', :controller => 'sellers'

  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
  post '/sessions/create' => 'sessions#create'

  root 'welcome#index'

end

app/models/seller.rb
class Seller < ActiveRecord::Base

  validates :password, :presence => true
  validates :password, :length => { :in => 6..200}
  validates :name, :email, :presence => true
  validates :email, :uniqueness => { :case_sensitive => false }
  validates :email, :format => { :with => /@/, :message => " is invalid" }

  def password
    password_hash ? @password ||= BCrypt::Password.new(password_hash) : nil
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

  def self.authenticate(email, test_password)
    seller = Seller.find_by_email(email)
    if seller && seller.password == test_password
      seller
    else
      nil
    end
  end

  # get the authorization url for this seller. This url will let the seller
  # register or login to WePay to approve our app.

  # returns a url
  def wepay_authorization_url(redirect_uri)
    Wetrade::Application::WEPAY.oauth2_authorize_url(redirect_uri, self.email, self.name)
  end

  # takes a code returned by wepay oauth2 authorization and makes an api call to generate oauth2 token for this seller.
  def request_wepay_access_token(code, redirect_uri)
    response = Wetrade::Application::WEPAY.oauth2_token(code, redirect_uri)
    if response['error']
      raise "Error - "+ response['error_description']
    elsif !response['access_token']
      raise "Error requesting access from WePay"
    else
      self.wepay_access_token = response['access_token']
      self.save

    #create WePay account
      self.create_wepay_account
    end
  end


  def has_wepay_account?
    self.wepay_account_id != 0 && !self.wepay_account_id.nil?
  end

  # creates a WePay account for this seller with the farm's name
  def create_wepay_account
    if self.has_wepay_access_token? && !self.has_wepay_account?
      params = { :name => self.firm, :description => "Selling " + self.produce }
      response = Wetrade::Application::WEPAY.call("/account/create", self.wepay_access_token, params)

      if response["account_id"]
        self.wepay_account_id = response["account_id"]
        return self.save
      else
        raise "Error - " + response["error_description"]
      end

    end
    raise "Error - cannot create WePay account"
  end

  def has_wepay_access_token?
    !self.wepay_access_token.nil?
  end

  # makes an api call to WePay to check if current access token for seller is still valid
  def has_valid_wepay_access_token?
    if self.wepay_access_token.nil?
      return false
    end
    response = Wetrade::Application::WEPAY.call("/user", self.wepay_access_token)
    response && response["user_id"] ? true : false
  end

  # creates a checkout object using WePay API for this seller
  def create_checkout(redirect_uri)
    # calculate app_fee as 10% of produce price
    app_fee = self.produce_price * 0.1

    params = {
      :account_id => self.wepay_account_id,
      :short_description => "Produce sold by #{self.firm}",
      :type => :GOODS,
      :currency => 'USD',
      :amount => self.produce_price,
      :fee => {
          :app_fee => app_fee,
          :fee_payer => 'payee'
      },
      :hosted_checkout => {
          :mode  => 'iframe',
          :redirect_uri => redirect_uri
      }
    }
    response = Wetrade::Application::WEPAY.call('/checkout/create', self.wepay_access_token, params)

    if !response
      raise "Error - no response from WePay"
    elsif response['error']
      raise "Error - " + response["error_description"]
    end

    return response
  end

end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @seller = Seller.find(params[:id])
    @is_admin = current_user && current_user.id == @seller.id
  end

  # GET /sellers/new
  def new
    if current_user
      redirect_to root_path, :notice => "You are already registered"
    end
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
    @seller = Seller.find(params[:id])
    if current_user.id != @seller.id
      redirect_to @seller
    end
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        session[:seller_id] = @seller.id
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:name, :email, :password, :firm, :produce, :produce_price, :wepay_access_token, :wepay_account_id)
    end

    # GET /sellers/oauth/1
    def oauth
      if !params[:code]
        return redirect_to('/')
      end

      redirect_uri = url_for(:controller => 'sellers', :action => 'oauth', :seller_id => params[:seller_id], :host => request.host_with_port)
      @seller = Seller.find(params[:seller_id])
      begin
        @farmer.request_wepay_access_token(params[:code], redirect_uri)
      rescue Exception => e
        error = e.message
      end

      if error
        redirect_to @seller, alert: error
      else
        redirect_to @seller, notice: 'We successfully connected you to WePay!'
      end
    end

    # GET /sellers/buy/1
    def buy
      redirect_uri = url_for(:controller => 'sellers', :action => 'payment_success', :seller_id => params[:seller_id], :host => request.host_with_port)
      @seller = Seller.find(params[:farmer_id])
      begin
        @checkout = @seller.create_checkout(redirect_uri)
      rescue Exception => e
        redirect_to @seller, alert: e.message
      end
    end

    # GET /sellers/payment_success/1
    def payment_success
      @seller = Seller.find(params[:seller_id])
      if !params[:checkout_id]
        return redirect_to @seller, alert: "Error - Checkout ID is expected"
      end
      if (params['error'] && params['error_description'])
        return redirect_to @seller, alert: "Error - #{params['error_description']}"
      end
      redirect_to @seller, notice: "Thanks for the payment! You should receive a confirmation email shortly."
    end

end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :firm %><br>
    <%= f.text_field :firm %>
  </div>
  <div class="field">
    <%= f.label :produce %><br>
    <%= f.text_field :produce %>
  </div>
  <div class="field">
    <%= f.label :produce_price %><br>
    <%= f.number_field :produce_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sellers/buy.html.erb
<h1>Buy <%= @seller.produce %> from <%= @seller.firm %> for <%= number_to_currency(@seller.produce_price, :unit => "$") %></h1>
<p><%= link_to "← back to " + @seller.name + "'s " + @seller.farm, @seller %></p>

<div id="wepay-iframe-div">
  <script type="text/javascript" src="https://www.wepay.com/js/iframe.wepay.js">
  </script>

  <script type="text/javascript">
    WePay.iframe_checkout("wepay-iframe-div", "<%= @checkout['checkout_uri'] %>");
  </script>
</div>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sellers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password hash</th>
      <th>Firm</th>
      <th>Produce</th>
      <th>Produce price</th>
      <th>Wepay access token</th>
      <th>Wepay account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.name %></td>
        <td><%= seller.email %></td>
        <td><%= seller.password_hash %></td>
        <td><%= seller.firm %></td>
        <td><%= seller.produce %></td>
        <td><%= seller.produce_price %></td>
        <td><%= seller.wepay_access_token %></td>
        <td><%= seller.wepay_account_id %></td>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>New Seller</h1>

<%= render 'form' %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @seller.firm %></h1>

<% if (@seller.has_wepay_account? && !@is_admin) %>
<br />
<%= link_to "Buy #{@seller.produce} Now!", "/sellers/buy/#{@seller.id}", :class => 'btn btn-danger btn-large', :id => 'buy-now-button' %>
<% end %>

<% if (@is_admin && (!@seller.has_valid_wepay_access_token? || !@seller.has_wepay_account?)) %>
  <p>
    <b>Please create an account to manage your money: </b>
  <% redirect_uri = url_for(:controller => 'sellers', :action => 'oauth', :seller_id => @seller.id, :host => request.host_with_port) %>
    <a class="btn btn-primary" href="<%= @seller.wepay_authorization_url(redirect_uri) %>">Click here to create your account</a>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @seller.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @seller.email %>
</p>

<p>
  <strong>Firm:</strong>
  <%= @seller.firm %>
</p>

<p>
  <strong>Produce:</strong>
  <%= @seller.produce %>
</p>

<p>
  <strong>Produce price:</strong>
  <%= @seller.produce_price %>
</p>

<% if (@is_admin) %>
<%= link_to 'Edit', edit_seller_path(@seller) %>
<% end %> |
<%= link_to 'Back', sellers_path %>