config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :sellers

  get 'welcome/index'
  get 'register' => 'sellers#new', :as => :register
  get '/sellers/:action(/:seller_id)', :controller => 'sellers'

  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
  post '/sessions/create' => 'sessions#create'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>WeTrade</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar">
  <span class="icon-bar">
  <span class="icon-bar">
</button>
<%= link_to 'WeFarm', root_path, :class => 'brand' %>
<div class="nav-collapse collapse">
  <ul class="nav pull-right">
    <% if current_user %>
    <li>
    <%= link_to 'Logout', logout_path %>
    </li>
    <% else %>
    <li>
    <%= link_to 'Register', register_path %>
    </li>
    <li>
    <%= link_to 'Login', login_path %>
    </li>
    <% end %>
  </ul>
</div>
</div>
</div>
</div>

<div class="container">

<div class="row-fluid">
<div class="span8">
<% if flash.notice %>
  <div class="alert alert-block alert-info">
    <button type="button" class="close" data-dismiss="alert">×
    <%= flash.notice %>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-block alert-error">
    <button type="button" class="close" data-dismiss="alert">×
    <%= flash.alert %>
  </div>
<% end %>
</div>
</div>

<%= yield %>

</div>

</body>
</html>